# Autogenerated wrapper script for GNUTime_jll for x86_64-apple-darwin
export gtime

JLLWrappers.@generate_wrapper_header("GNUTime")
JLLWrappers.@declare_executable_product(gtime)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        gtime,
        "bin/time",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
